services:
  metrolinea-ai:
    build: .
    container_name: metrolinea-ai
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/srv/app
      - ./data:/srv/data
      - ./models:/srv/models
    restart: unless-stopped
